# Site settings
title:			Jonatanhal
tagline:		'$PUNCHLINE'

description: 		"â˜ƒ"
baseurl:   	        /

url: 			"https://jonatanhal.github.io" # the base hostname & protocol for your site

author:
        name:		'Jonatanhal'
        url:		'https://twitter.com/jonatanhal'

twitter_username: 	jonatanhal
github_username:	jonatanhal

# Build settings
markdown:		kramdown
highlighter: 		pygments

permalinks:  		pretty
relative_permalinks:	true

paginate:		1


